### ISSUE TITLE
Dashboard fails to load with "Configuration error"

### ISSUE THREAD

**Issue by thegrahamwalsh** [dwainscheeren/dwains-dashboard-next#3]
window.customStrategies.some is not a function

Version: v1.5.3
Home Assistant Core: 2026.7.0
Frontend: 20260624.3
Browsers tested: Chrome 148 (macOS), Chrome 138 (Linux), Safari (iOS 18.7) — same error on all three

Summary

Since updating to v1.5.3 (released 2026-07-01, same day as HA Core 2026.7.0), any dashboard using the custom:dwains-dashboard-next strategy fails to load with a generic "Configuration error" in the UI. The actual JS error is:

TypeError: window.customStrategies.some is not a function
(In 'window.customStrategies.some(e=>e?.type===d&&"dashboard"===e?.strategyType)',
'window.customStrategies.some' is undefined)
    at dwains-dashboard-next.js:1:17692 (module code)

This is 100% reproducible — confirmed across three different browsers/devices, and on a brand new dashboard created from scratch (not just an old/cached config).

Downstream effect

Because this throws synchronously near the top of the module, it appears to halt the rest of the module's init — including registration of the strategy's config-editor custom element. Opening "Edit dashboard" on an affected dashboard shows:

Visual editor not supported
- this._configElement.setConfig is not a function

i.e. the editor element was never customElements.define()'d, because execution never reached that point.

Environment details

Lovelace resource registered correctly: /hacsfiles/dwains-dashboard-next/dwains-dashboard-next.js
HACS shows the repo installed and up to date at v1.5.3, no pending update
Reproduced on a freshly created dashboard with a minimal config ({"strategy": {"type": "custom:dwains-dashboard-next"}}) — not specific to any prior device_admission state

Suspected cause

Looks like the window.customStrategies array isn't guaranteed to exist yet when this line runs. Most custom-strategy registration patterns guard against this with:

jswindow.customStrategies = window.customStrategies || [];
window.customStrategies.push({...});

If the .some() check that's failing runs before this defensive init (or before HA's own frontend has seeded the array), it would produce exactly this error. Possibly a timing/init-order regression introduced while patching for the 2026.5+ window.customStrategies API, or for 2026.7.0 frontend changes specifically (given the release timing).

Happy to provide any further diagnostics needed.
Content

**Comment by dwainscheeren** [comment]
Fixed in Dwains Dashboard Next 1.6.0.

The cause was that `window.customStrategies` could already exist but not be an array. The previous initialization only handled a missing value, so calling `.some()` stopped the module before the dashboard strategy and editor were registered.

Next now validates both `window.customStrategies` and `window.customCards` before using array methods. If another frontend resource has left either registry in an unexpected format, only the optional Add dashboard/card-picker registration is skipped and a warning is logged; the dashboard itself continues loading. I also reproduced the non-array case in a browser regression test and verified that the strategy, view, dashboard card and editor-related components still register.

Release: https://github.com/dwainscheeren/dwains-dashboard-next/releases/tag/v1.6.0

Thanks for the clear diagnostics.
